version: '3.8'

services:
  # Banco de Dados PostgreSQL
  sismob-db:
    image: postgis/postgis:15-3.3-alpine
    container_name: sismob-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_SERVICE_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - sismob_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Interface Visual (Opcional - acesse em http://localhost:5050)
  pgadmin:
    image: dpage/pgadmin4
    container_name: sismob-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sismob.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - sismob-db

  # Backend Application
  sismob-app:
    build: .
    container_name: sismob-backend
    restart: always
    ports:
      - "8097:8097"
    environment:
      DB_HOST: sismob-postgres # Using the container_name of the DB service
      DB_PORT: 5432
      DB_SERVICE_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: SISMOB_SECRET_KEY_2026
      APP_PREFIX: api
    depends_on:
      - sismob-db

volumes:
  sismob_pgdata:
